name: "Publish"

on:
  push:
    tags:
      - "release-*"
jobs:
  publish:
    name: "Publish from master"
    timeout-minutes: 60
    runs-on: ubuntu-22.04
    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@v3"
      - name: "Setup Node"
        uses: "actions/setup-node@v3"
        with:
          node-version: current
          cache: "npm"
      - name: Update NPM
        run: npm install -g npm
      - name: Install
        run: npm install
      - name: Build
        run: npm run build
      - name: Publish
        run: |
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
          npm publish --access public
        shell: bash
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
